#name: Deploy to Cloud Run
# on:
#   push:
#     branches:
#       - develop
# env:
#   PROJECT_ID: ${{ secrets.PROJECT_ID_DEV }}
#   RUN_REGION: us-east4

# jobs:
#   deploy:
#     name: Deploy to Cloud Run
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       # Setup gcloud CLI
#       - id: 'auth'
#         uses: 'google-github-actions/auth@v0'
#         with:
#           credentials_json: '${{ secrets.SERVICE_ACCOUNT_CREDS_DEV }}'

#       - name: 'Set up Cloud SDK'
#         uses: 'google-github-actions/setup-gcloud@v0'

#       - name: 'Use gcloud CLI'
#         run: 'gcloud info'
          
#       # Build and push image to Google Container Registry
#       - name: Build
#         run: gcloud builds submit --tag=gcr.io/my-project/image--tag=gcr.io/$PROJECT_ID/$PROJECT_ID:$GITHUB_SHA
        
#       - name: web_deploy
#         run: gcloud run deploy $PROJECT_ID --image=gcr.io/$PROJECT_ID/$PROJECT_ID:west --platform managed --region $RUN_REGION

name: Deploy to Cloud Run
on:
  push:
    branches:
      - develop
env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-east4
  SA_KEY_JSON: '${{ secrets.RUN_SA_KEY }}'
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.RUN_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$PROJECT_ID:$GITHUB_SHA --gcs-log-dir=gs://cloudrun-github
    

      - name: Deploy
        run: gcloud run deploy $PROJECT_ID --image gcr.io/$PROJECT_ID/$PROJECT_ID:$GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated

